* Handwritten example; this file was not generated by an API.
DEFINE CLASS VfpAiHelloForm AS Form
    Caption = "Ejemplo de formulario en PRG"
    Width = 480
    Height = 220
    AutoCenter = .T.
    BorderStyle = 2
    MaxButton = .F.
    MinButton = .F.
    DataSession = 2

    ADD OBJECT lblName AS Label WITH ;
        Left = 20, Top = 24, Width = 420, Height = 24, ;
        Caption = "Tu nombre:"

    ADD OBJECT txtName AS TextBox WITH ;
        Left = 20, Top = 56, Width = 420, Height = 28, ;
        Value = "", MaxLength = 80, TabIndex = 1

    ADD OBJECT cmdGreet AS CommandButton WITH ;
        Left = 20, Top = 104, Width = 120, Height = 32, ;
        Caption = "Saludar", TabIndex = 2

    ADD OBJECT lblResult AS Label WITH ;
        Left = 20, Top = 160, Width = 420, Height = 24, Caption = ""

    ADD OBJECT cmdClose AS CommandButton WITH ;
        Left = 320, Top = 104, Width = 120, Height = 32, ;
        Caption = "Cerrar", Cancel = .T., TabIndex = 3

    PROCEDURE cmdGreet.Click
        LOCAL lcName
        lcName = ALLTRIM(Thisform.txtName.Value)
        IF EMPTY(lcName)
            Thisform.lblResult.Caption = "Escribi un nombre para continuar."
            Thisform.txtName.SetFocus()
            RETURN
        ENDIF
        Thisform.lblResult.Caption = "Hola, " + lcName + "."
    ENDPROC

    PROCEDURE cmdClose.Click
        Thisform.Release()
    ENDPROC
ENDDEFINE
